config/routes.rb
Rails.application.routes.draw do
  get 'servicelog/cbwe'
  get 'servicelog/twe'
  get 'servicelog/ee'
  get 'servicelog/ltfa'
  get 'servicelog/ijc'
  get 'servicelog/pp'
  get 'servicelog/ddd'
  get 'servicelog/dddpp'
  get 'servicelog/preets'
  get 'servicelog/schooleval'
  resources :votltfas
  resources :twers
  resources :otfs
  resources :features
  resources :otfcompletions
  resources :hourlyrates
  resources :eestatuscodes
  get 'ee/index'
  get 'ee/report'
  match '/users',   to: 'users#index',   via: 'get'

  get 'users/index'
  get 'preets/index'
  get 'restab/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

get 'ltfa/julynineteen'
get 'ltfa/junnineteen'
get 'ltfa/augnineteen'
get 'ltfa/sepnineteen'
get 'ltfa/sepnineteen'
get 'ltfa/octnineteen'
get 'ltfa/novnineteen'
get 'ltfa/novnineteen'
get 'ltfa/decnineteen'
get 'authorizations/deleted'
get 'interventions/deleted'
get 'employers/deleted'
get 'assignments/deleted'
get 'clientemployer/deleted'
get 'jobcoach/deleted'
get 'punches/deleted'

  get 'grants/index'
  get 'grant/home'


  resources :staffs do
          collection { post :import }
  end
  resources :devices do
          collection { post :import }
  end
  get 'monthlybilled/index'

  get 'monthlybilled/jan2021'
  get 'monthlybilled/jan2020'
  get 'monthlybilled/jan2019'
  get 'monthlybilled/jan2018'
  get 'monthlybilled/jan2017'
  get 'monthlybilled/jan2016'
  get 'monthlybilled/jan2015'
 
  get 'monthlybilled/feb2021'
  get 'monthlybilled/feb2020'
  get 'monthlybilled/feb2019'
  get 'monthlybilled/feb2018'
  get 'monthlybilled/feb2017'
  get 'monthlybilled/feb2016'
  get 'monthlybilled/feb2015'

  get 'monthlybilled/mar2021'
  get 'monthlybilled/mar2020'
  get 'monthlybilled/mar2019'
  get 'monthlybilled/mar2018'
  get 'monthlybilled/mar2017'
  get 'monthlybilled/mar2016'
  get 'monthlybilled/mar2015'

  get 'monthlybilled/apr2021'
  get 'monthlybilled/apr2020'
  get 'monthlybilled/apr2019'
  get 'monthlybilled/apr2018'
  get 'monthlybilled/apr2017'
  get 'monthlybilled/apr2016'
  get 'monthlybilled/apr2015'

  get 'monthlybilled/may2021'
  get 'monthlybilled/may2020'
  get 'monthlybilled/may2019'
  get 'monthlybilled/may2018'
  get 'monthlybilled/may2017'
  get 'monthlybilled/may2016'
  get 'monthlybilled/may2015'

  get 'monthlybilled/jun2021'
  get 'monthlybilled/jun2020'
  get 'monthlybilled/jun2019'
  get 'monthlybilled/jun2018'
  get 'monthlybilled/jun2017'
  get 'monthlybilled/jun2016'
  get 'monthlybilled/jun2015'

  get 'monthlybilled/jul2021'
  get 'monthlybilled/jul2020'
  get 'monthlybilled/jul2019'
  get 'monthlybilled/jul2018'
  get 'monthlybilled/jul2017'
  get 'monthlybilled/jul2016'
  get 'monthlybilled/jul2015'

  get 'monthlybilled/aug2021'
  get 'monthlybilled/aug2020'
  get 'monthlybilled/aug2019'
  get 'monthlybilled/aug2018'
  get 'monthlybilled/aug2017'
  get 'monthlybilled/aug2016'
  get 'monthlybilled/aug2015'

  get 'monthlybilled/sep2021'
  get 'monthlybilled/sep2020'
  get 'monthlybilled/sep2019'
  get 'monthlybilled/sep2018'
  get 'monthlybilled/sep2017'
  get 'monthlybilled/sep2016'
  get 'monthlybilled/sep2015'

  get 'monthlybilled/oct2021'
  get 'monthlybilled/oct2020'
  get 'monthlybilled/oct2019'
  get 'monthlybilled/oct2018'
  get 'monthlybilled/oct2017'
  get 'monthlybilled/oct2016'
  get 'monthlybilled/oct2015'

  get 'monthlybilled/nov2021'
  get 'monthlybilled/nov2020'
  get 'monthlybilled/nov2019'
  get 'monthlybilled/nov2018'
  get 'monthlybilled/nov2017'
  get 'monthlybilled/nov2016'
  get 'monthlybilled/nov2015'

  get 'monthlybilled/dec2021'
  get 'monthlybilled/dec2020'
  get 'monthlybilled/dec2019'
  get 'monthlybilled/dec2018'
  get 'monthlybilled/dec2017'
  get 'monthlybilled/dec2016'
  get 'monthlybilled/dec2015'

  get 'monthlybilled/year2015'
  get 'monthlybilled/year2016'
  get 'monthlybilled/year2017'
  get 'monthlybilled/year2018'
  get 'monthlybilled/year2019'
  get 'monthlybilled/year2020'
  get 'monthlybilled/year2021'



  get 'timesheets/index'

  get 'timesheets/jan2021'
  get 'timesheets/jan2020'
  get 'timesheets/jan2019'
  get 'timesheets/jan2018'
  get 'timesheets/jan2017'
  get 'timesheets/jan2016'
  get 'timesheets/jan2015'
  
  get 'timesheets/feb2021'
  get 'timesheets/feb2020'
  get 'timesheets/feb2019'
  get 'timesheets/feb2018'
  get 'timesheets/feb2017'
  get 'timesheets/feb2016'
  get 'timesheets/feb2015'

  get 'timesheets/mar2021'
  get 'timesheets/mar2020'
  get 'timesheets/mar2019'
  get 'timesheets/mar2018'
  get 'timesheets/mar2017'
  get 'timesheets/mar2016'
  get 'timesheets/mar2015'

  get 'timesheets/apr2021'
  get 'timesheets/apr2020'
  get 'timesheets/apr2019'
  get 'timesheets/apr2018'
  get 'timesheets/apr2017'
  get 'timesheets/apr2016'
  get 'timesheets/apr2015'

  get 'timesheets/may2021'
  get 'timesheets/may2020'
  get 'timesheets/may2019'
  get 'timesheets/may2018'
  get 'timesheets/may2017'
  get 'timesheets/may2016'
  get 'timesheets/may2015'

  get 'timesheets/jun2021'
  get 'timesheets/jun2020'
  get 'timesheets/jun2019'
  get 'timesheets/jun2018'
  get 'timesheets/jun2017'
  get 'timesheets/jun2016'
  get 'timesheets/jun2015'


  get 'timesheets/jul2021'
  get 'timesheets/jul2020'
  get 'timesheets/jul2019'
  get 'timesheets/jul2018'
  get 'timesheets/jul2017'
  get 'timesheets/jul2016'
  get 'timesheets/jul2015'

  get 'timesheets/aug2021'
  get 'timesheets/aug2020'
  get 'timesheets/aug2019'
  get 'timesheets/aug2018'
  get 'timesheets/aug2017'
  get 'timesheets/aug2016'
  get 'timesheets/aug2015'

  get 'timesheets/sep2021'
  get 'timesheets/sep2020'
  get 'timesheets/sep2019'
  get 'timesheets/sep2018'
  get 'timesheets/sep2017'
  get 'timesheets/sep2016'
  get 'timesheets/sep2015'

  get 'timesheets/oct2021'
  get 'timesheets/oct2020'
  get 'timesheets/oct2019'
  get 'timesheets/oct2018'
  get 'timesheets/oct2017'
  get 'timesheets/oct2016'
  get 'timesheets/oct2015'

  get 'timesheets/nov2021'
  get 'timesheets/nov2020'
  get 'timesheets/nov2019'
  get 'timesheets/nov2018'
  get 'timesheets/nov2017'
  get 'timesheets/nov2016'
  get 'timesheets/nov2015'

  get 'timesheets/dec2021'
  get 'timesheets/dec2020'
  get 'timesheets/dec2019'
  get 'timesheets/dec2018'
  get 'timesheets/dec2017'
  get 'timesheets/dec2016'
  get 'timesheets/dec2015'

  get 'timesheets/year2015'
  get 'timesheets/year2016'
  get 'timesheets/year2017'
  get 'timesheets/year2018'
  get 'timesheets/year2019'
  get 'timesheets/year2020'
  get 'timesheets/year2021'



  # get 'calendar/index'
  get 'calendar/jan2021'
  get 'calendar/jan2020'
  get 'calendar/jan2019'
  get 'calendar/jan2018'
  get 'calendar/jan2017'
  get 'calendar/jan2016'
  get 'calendar/jan2015'
  get 'calendar/jan'
  get 'calendar/feb'
  get 'calendar/feb2021'
  get 'calendar/feb2020'
  get 'calendar/feb2019'
  get 'calendar/feb2018'
  get 'calendar/feb2017'
  get 'calendar/feb2016'
  get 'calendar/feb2015'
  get 'calendar/mar'
  get 'calendar/mar2021'
  get 'calendar/mar2020'
  get 'calendar/mar2019'
  get 'calendar/mar2018'
  get 'calendar/mar2017'
  get 'calendar/mar2016'
  get 'calendar/mar2015'
  get 'calendar/apr'
  get 'calendar/apr2021'
  get 'calendar/apr2020'
  get 'calendar/apr2019'
  get 'calendar/apr2018'
  get 'calendar/apr2017'
  get 'calendar/apr2016'
  get 'calendar/apr2015'
  get 'calendar/may'
  get 'calendar/may2021'
  get 'calendar/may2020'
  get 'calendar/may2019'
  get 'calendar/may2018'
  get 'calendar/may2017'
  get 'calendar/may2015'
  get 'calendar/jun'
  get 'calendar/jun2021'
  get 'calendar/jun2020'
  get 'calendar/jun2019'
  get 'calendar/jun2018'
  get 'calendar/jun2017'
  get 'calendar/jun2016'
  get 'calendar/jun2015'
  get 'calendar/jul'
  get 'calendar/jul2021'
  get 'calendar/jul2020'
  get 'calendar/jul2019'
  get 'calendar/jul2018'
  get 'calendar/jul2017'
  get 'calendar/jul2016'
  get 'calendar/jul2015'
  get 'calendar/aug'
  get 'calendar/aug2021'
  get 'calendar/aug2020'
  get 'calendar/aug2019'
  get 'calendar/aug2018'
  get 'calendar/aug2017'
  get 'calendar/aug2016'
  get 'calendar/aug2015'
  get 'calendar/sep'
  get 'calendar/sep2021'
  get 'calendar/sep2020'
  get 'calendar/sep2019'
  get 'calendar/sep2018'
  get 'calendar/sep2017'
  get 'calendar/sep2016'
  get 'calendar/sep2015'
  get 'calendar/oct'
  get 'calendar/oct2021'
  get 'calendar/oct2020'
  get 'calendar/oct2019'
  get 'calendar/oct2018'
  get 'calendar/oct2017'
  get 'calendar/oct2016'
  get 'calendar/oct2015'
  get 'calendar/nov'
  get 'calendar/nov2021'
  get 'calendar/nov2020'
  get 'calendar/nov2019'
  get 'calendar/nov2018'
  get 'calendar/nov2017'
  get 'calendar/nov2016'
  get 'calendar/nov2015'
  get 'calendar/dec'
  get 'calendar/dec2021'
  get 'calendar/dec2020'
  get 'calendar/dec2019'
  get 'calendar/dec2018'
  get 'calendar/dec2017'
  get 'calendar/dec2016'
  get 'calendar/dec2015'
  get 'calendar/ddd_q2'
  get 'calendar/ddd_q3'
  get 'calendar/ddd_q4'
  get 'calendar/report'
  get 'calendar/report2021'
  get 'calendar/report2020'
  get 'calendar/report2019'
  get 'calendar/report2018'
  get 'calendar/report2017'
  get 'calendar/report2016'
  get 'calendar/report2015'

  resources :punches
  get 'ltfa/index'
  get 'ltfa/jan'
  get 'ltfa/feb'
  get 'ltfa/mar'
  get 'ltfa/apr'
  get 'ltfa/may'
  get 'ltfa/jun'
  get 'ltfa/jul'
  get 'ltfa/aug'
  get 'ltfa/sep'
  get 'ltfa/oct'
  get 'ltfa/nov'
  get 'ltfa/dec'
  get 'ltfa/ltfatwentytwenty'

  resources :activityreports
  get 'monthlybilled/index'
  devise_for :controllers
  resources :authorizations
  get 'unassigned/index'
  get 'logs/index'
  get 'ltfa/show'
  root 'pages#home'



  get 'ee/report'
  get 'authorizations/report_LTFA_TwentyTwenty'

    devise_for :users

  get 'openvoucher/index'
  get 'graphs/index'
  get 'reports/index'
  get 'monthly/index'
  get 'unpaid/index'
  get 'completed/index'
  get 'counselor/index'
  get 'pp/index'
  get 'csv/index'
  get 'timesheets/index'
  get 'cbwe/index'
  get 'ddd/index'
  get 'jobcoaches/index'

app/models/votltfa.rb
class Votltfa < ApplicationRecord
end

app/controllers/votltfas_controller.rb
class VotltfasController < ApplicationController
  before_action :set_votltfa, only: [:show, :edit, :update, :destroy]

  # GET /votltfas
  # GET /votltfas.json
  def index
    @votltfas = Votltfa.all
  end

  # GET /votltfas/1
  # GET /votltfas/1.json
  def show
  end

  # GET /votltfas/new
  def new
    @votltfa = Votltfa.new
    @clientid = params[:clientid]
    @clients = Client.all
    @employees = Employee.all
  end

  # GET /votltfas/1/edit
  def edit
  end

  # POST /votltfas
  # POST /votltfas.json
  def create
    @votltfa = Votltfa.new(votltfa_params)

    respond_to do |format|
      if @votltfa.save
        format.html { redirect_to @votltfa, notice: 'Votltfa was successfully created.' }
        format.json { render :show, status: :created, location: @votltfa }
      else
        format.html { render :new }
        format.json { render json: @votltfa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votltfas/1
  # PATCH/PUT /votltfas/1.json
  def update
    respond_to do |format|
      if @votltfa.update(votltfa_params)
        format.html { redirect_to @votltfa, notice: 'Votltfa was successfully updated.' }
        format.json { render :show, status: :ok, location: @votltfa }
      else
        format.html { render :edit }
        format.json { render json: @votltfa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votltfas/1
  # DELETE /votltfas/1.json
  def destroy
    @votltfa.destroy
    respond_to do |format|
      format.html { redirect_to votltfas_url, notice: 'Votltfa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_votltfa
      @votltfa = Votltfa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def votltfa_params
      params.require(:votltfa).permit(:date, :provider, :client, :rate, :reason, :empsig, :providerstaff, :empname)
    end
end

app/helpers/votltfas_helper.rb
module VotltfasHelper
end

app/views/votltfas/_form.html.erb
<%= form_with(model: votltfa, local: true) do |form| %>
  <% if votltfa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(votltfa.errors.count, "error") %> prohibited this votltfa from being saved:</h2>

      <ul>
        <% votltfa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    The above named individual received LTFA and services ended or are scheduled to end:
    <br>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    DVRS Supported Employment LTFA Provider:
    <%= form.text_field :provider, :value => "Center for Educational Advancement", :readonly => true %>
  </div>

  <div class="field">
Consumer Name: *Participant ID
<%= form.label :client %>
  <%= form.select :ClientID, options_from_collection_for_select(@clients.all.order(:clientLastName), "id",:fullname_with_id, @clientid )%>

    <%#= form.text_field :client %>
  </div>

  <div class="field">
Service was billable to the following LTFA account/rate (check as applicable):
<% @options={
             '1' => 'Regular',
             '2' => 'ASL'
          } %>

     <%= form.collection_select :rate, @options, :first, :last, class: "form-control" %>
<%#= form.label :rate %>
    <%#= form.text_field :rate %>
  </div>

  <div class="field">
Please check the applicable reason for termination.
<% @options={
             '1' => 'Graduating LTFA',
             '2' => 'Transferred to DDD LTFA',
             '3' => 'Transferred to another LTFA Provider',
             '4' => 'Referred back to field office (complete referral form) *',
             '5' => 'Terminated from job',
             '6' => 'self-terminated from job',
             '7' => 'Moved',
             '8' => 'Lost to contact / uncooperative',
             '9' => 'Refuses Services',
             '10' => 'Medical',
             '11' => 'Deceased',
             '12' => 'other'
          } %>
     <%= form.collection_select :reason, @options, :first, :last, class: "form-control" %>

    <%#= form.text_field :reason %>
  </div>

  <div class="field">
Please sign to verify above:
    <%= form.label :empsig %>
    <%= form.text_field :empsig %>
  </div>

  <div class="field">
Provider Staff:
    <%= form.label :providerstaff %>
    <%= form.text_field :providerstaff %>
  </div>

  <div class="field">
Print Name:
    <%= form.label :empname %>
    <%= form.text_field :empname %>
  </div>
  1) Provider submits this form with monthly billing.
  <br>
2) Provider Kkeeps copy.
  <br>
* 3) When referring back to the local DVRS office, the provider submits this form, a completed referral,
  <br>
and 3-6 months' service logs.
  <br>
R-2/20
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votltfas/edit.html.erb
<h1>Editing Votltfa</h1>

<%= render 'form', votltfa: @votltfa %>

<%= link_to 'Show', @votltfa %> |
<%= link_to 'Back', votltfas_path %>

app/views/votltfas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votltfas</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Provider</th>
      <th>Client</th>
      <th>Rate</th>
      <th>Reason</th>
      <th>Empsig</th>
      <th>Providerstaff</th>
      <th>Empname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votltfas.each do |votltfa| %>
      <tr>
        <td><%= votltfa.date %></td>
        <td><%= votltfa.provider %></td>
        <td><%= votltfa.client %></td>
        <td><%= votltfa.rate %></td>
        <td><%= votltfa.reason %></td>
        <td><%= votltfa.empsig %></td>
        <td><%= votltfa.providerstaff %></td>
        <td><%= votltfa.empname %></td>
        <td><%= link_to 'Show', votltfa %></td>
        <td><%= link_to 'Edit', edit_votltfa_path(votltfa) %></td>
        <td><%= link_to 'Destroy', votltfa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Votltfa', new_votltfa_path %>

app/views/votltfas/new.html.erb
<h1>New Votltfa</h1>

<%= render 'form', votltfa: @votltfa %>

<%= link_to 'Back', votltfas_path %>

app/views/votltfas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @votltfa.date %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @votltfa.provider %>
</p>

<p>
  <strong>Client:</strong>
  <%= @votltfa.client %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @votltfa.rate %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @votltfa.reason %>
</p>

<p>
  <strong>Empsig:</strong>
  <%= @votltfa.empsig %>
</p>

<p>
  <strong>Providerstaff:</strong>
  <%= @votltfa.providerstaff %>
</p>

<p>
  <strong>Empname:</strong>
  <%= @votltfa.empname %>
</p>

<%= link_to 'Edit', edit_votltfa_path(@votltfa) %> |
<%= link_to 'Back', votltfas_path %>