config/routes.rb
Rails.application.routes.draw do
  get 'servicelog/cbwe'
  get 'servicelog/twe'
  get 'servicelog/ee'
  get 'servicelog/ltfa'
  get 'servicelog/ijc'
  get 'servicelog/pp'
  get 'servicelog/ddd'
  get 'servicelog/dddpp'
  get 'servicelog/preets'
  get 'servicelog/schooleval'
  resources :votltfas
  resources :twers
  resources :otfs
  resources :features
  resources :otfcompletions
  resources :hourlyrates
  resources :eestatuscodes
  get 'ee/index'
  get 'ee/report'
  match '/users',   to: 'users#index',   via: 'get'

  get 'users/index'
  get 'preets/index'
  get 'restab/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

get 'ltfa/julynineteen'
get 'ltfa/junnineteen'
get 'ltfa/augnineteen'
get 'ltfa/sepnineteen'
get 'ltfa/sepnineteen'
get 'ltfa/octnineteen'
get 'ltfa/novnineteen'
get 'ltfa/novnineteen'
get 'ltfa/decnineteen'
get 'authorizations/deleted'
get 'interventions/deleted'
get 'employers/deleted'
get 'assignments/deleted'
get 'clientemployer/deleted'
get 'jobcoach/deleted'
get 'punches/deleted'

  get 'grants/index'
  get 'grant/home'


  resources :staffs do
          collection { post :import }
  end
  resources :devices do
          collection { post :import }
  end
  get 'monthlybilled/index'

  get 'monthlybilled/jan2021'
  get 'monthlybilled/jan2020'
  get 'monthlybilled/jan2019'
  get 'monthlybilled/jan2018'
  get 'monthlybilled/jan2017'
  get 'monthlybilled/jan2016'
  get 'monthlybilled/jan2015'
 
  get 'monthlybilled/feb2021'
  get 'monthlybilled/feb2020'
  get 'monthlybilled/feb2019'
  get 'monthlybilled/feb2018'
  get 'monthlybilled/feb2017'
  get 'monthlybilled/feb2016'
  get 'monthlybilled/feb2015'

  get 'monthlybilled/mar2021'
  get 'monthlybilled/mar2020'
  get 'monthlybilled/mar2019'
  get 'monthlybilled/mar2018'
  get 'monthlybilled/mar2017'
  get 'monthlybilled/mar2016'
  get 'monthlybilled/mar2015'

  get 'monthlybilled/apr2021'
  get 'monthlybilled/apr2020'
  get 'monthlybilled/apr2019'
  get 'monthlybilled/apr2018'
  get 'monthlybilled/apr2017'
  get 'monthlybilled/apr2016'
  get 'monthlybilled/apr2015'

  get 'monthlybilled/may2021'
  get 'monthlybilled/may2020'
  get 'monthlybilled/may2019'
  get 'monthlybilled/may2018'
  get 'monthlybilled/may2017'
  get 'monthlybilled/may2016'
  get 'monthlybilled/may2015'

  get 'monthlybilled/jun2021'
  get 'monthlybilled/jun2020'
  get 'monthlybilled/jun2019'
  get 'monthlybilled/jun2018'
  get 'monthlybilled/jun2017'
  get 'monthlybilled/jun2016'
  get 'monthlybilled/jun2015'

  get 'monthlybilled/jul2021'
  get 'monthlybilled/jul2020'
  get 'monthlybilled/jul2019'
  get 'monthlybilled/jul2018'
  get 'monthlybilled/jul2017'
  get 'monthlybilled/jul2016'
  get 'monthlybilled/jul2015'

  get 'monthlybilled/aug2021'
  get 'monthlybilled/aug2020'
  get 'monthlybilled/aug2019'
  get 'monthlybilled/aug2018'
  get 'monthlybilled/aug2017'
  get 'monthlybilled/aug2016'
  get 'monthlybilled/aug2015'

  get 'monthlybilled/sep2021'
  get 'monthlybilled/sep2020'
  get 'monthlybilled/sep2019'
  get 'monthlybilled/sep2018'
  get 'monthlybilled/sep2017'
  get 'monthlybilled/sep2016'
  get 'monthlybilled/sep2015'

  get 'monthlybilled/oct2021'
  get 'monthlybilled/oct2020'
  get 'monthlybilled/oct2019'
  get 'monthlybilled/oct2018'
  get 'monthlybilled/oct2017'
  get 'monthlybilled/oct2016'
  get 'monthlybilled/oct2015'

  get 'monthlybilled/nov2021'
  get 'monthlybilled/nov2020'
  get 'monthlybilled/nov2019'
  get 'monthlybilled/nov2018'
  get 'monthlybilled/nov2017'
  get 'monthlybilled/nov2016'
  get 'monthlybilled/nov2015'

  get 'monthlybilled/dec2021'
  get 'monthlybilled/dec2020'
  get 'monthlybilled/dec2019'
  get 'monthlybilled/dec2018'
  get 'monthlybilled/dec2017'
  get 'monthlybilled/dec2016'
  get 'monthlybilled/dec2015'

  get 'monthlybilled/year2015'
  get 'monthlybilled/year2016'
  get 'monthlybilled/year2017'
  get 'monthlybilled/year2018'
  get 'monthlybilled/year2019'
  get 'monthlybilled/year2020'
  get 'monthlybilled/year2021'



  get 'timesheets/index'

  get 'timesheets/jan2021'
  get 'timesheets/jan2020'
  get 'timesheets/jan2019'
  get 'timesheets/jan2018'
  get 'timesheets/jan2017'
  get 'timesheets/jan2016'
  get 'timesheets/jan2015'
  
  get 'timesheets/feb2021'
  get 'timesheets/feb2020'
  get 'timesheets/feb2019'
  get 'timesheets/feb2018'
  get 'timesheets/feb2017'
  get 'timesheets/feb2016'
  get 'timesheets/feb2015'

  get 'timesheets/mar2021'
  get 'timesheets/mar2020'
  get 'timesheets/mar2019'
  get 'timesheets/mar2018'
  get 'timesheets/mar2017'
  get 'timesheets/mar2016'
  get 'timesheets/mar2015'

  get 'timesheets/apr2021'
  get 'timesheets/apr2020'
  get 'timesheets/apr2019'
  get 'timesheets/apr2018'
  get 'timesheets/apr2017'
  get 'timesheets/apr2016'
  get 'timesheets/apr2015'

  get 'timesheets/may2021'
  get 'timesheets/may2020'
  get 'timesheets/may2019'
  get 'timesheets/may2018'
  get 'timesheets/may2017'
  get 'timesheets/may2016'
  get 'timesheets/may2015'

  get 'timesheets/jun2021'
  get 'timesheets/jun2020'
  get 'timesheets/jun2019'
  get 'timesheets/jun2018'
  get 'timesheets/jun2017'
  get 'timesheets/jun2016'
  get 'timesheets/jun2015'


  get 'timesheets/jul2021'
  get 'timesheets/jul2020'
  get 'timesheets/jul2019'
  get 'timesheets/jul2018'
  get 'timesheets/jul2017'
  get 'timesheets/jul2016'
  get 'timesheets/jul2015'

  get 'timesheets/aug2021'
  get 'timesheets/aug2020'
  get 'timesheets/aug2019'
  get 'timesheets/aug2018'
  get 'timesheets/aug2017'
  get 'timesheets/aug2016'
  get 'timesheets/aug2015'

  get 'timesheets/sep2021'
  get 'timesheets/sep2020'
  get 'timesheets/sep2019'
  get 'timesheets/sep2018'
  get 'timesheets/sep2017'
  get 'timesheets/sep2016'
  get 'timesheets/sep2015'

  get 'timesheets/oct2021'
  get 'timesheets/oct2020'
  get 'timesheets/oct2019'
  get 'timesheets/oct2018'
  get 'timesheets/oct2017'
  get 'timesheets/oct2016'
  get 'timesheets/oct2015'

  get 'timesheets/nov2021'
  get 'timesheets/nov2020'
  get 'timesheets/nov2019'
  get 'timesheets/nov2018'
  get 'timesheets/nov2017'
  get 'timesheets/nov2016'
  get 'timesheets/nov2015'

  get 'timesheets/dec2021'
  get 'timesheets/dec2020'
  get 'timesheets/dec2019'
  get 'timesheets/dec2018'
  get 'timesheets/dec2017'
  get 'timesheets/dec2016'
  get 'timesheets/dec2015'

  get 'timesheets/year2015'
  get 'timesheets/year2016'
  get 'timesheets/year2017'
  get 'timesheets/year2018'
  get 'timesheets/year2019'
  get 'timesheets/year2020'
  get 'timesheets/year2021'



  # get 'calendar/index'
  get 'calendar/jan2021'
  get 'calendar/jan2020'
  get 'calendar/jan2019'
  get 'calendar/jan2018'
  get 'calendar/jan2017'
  get 'calendar/jan2016'
  get 'calendar/jan2015'
  get 'calendar/jan'
  get 'calendar/feb'
  get 'calendar/feb2021'
  get 'calendar/feb2020'
  get 'calendar/feb2019'
  get 'calendar/feb2018'
  get 'calendar/feb2017'
  get 'calendar/feb2016'
  get 'calendar/feb2015'
  get 'calendar/mar'
  get 'calendar/mar2021'
  get 'calendar/mar2020'
  get 'calendar/mar2019'
  get 'calendar/mar2018'
  get 'calendar/mar2017'
  get 'calendar/mar2016'
  get 'calendar/mar2015'
  get 'calendar/apr'
  get 'calendar/apr2021'
  get 'calendar/apr2020'
  get 'calendar/apr2019'
  get 'calendar/apr2018'
  get 'calendar/apr2017'
  get 'calendar/apr2016'
  get 'calendar/apr2015'
  get 'calendar/may'
  get 'calendar/may2021'
  get 'calendar/may2020'
  get 'calendar/may2019'
  get 'calendar/may2018'
  get 'calendar/may2017'
  get 'calendar/may2015'
  get 'calendar/jun'
  get 'calendar/jun2021'
  get 'calendar/jun2020'
  get 'calendar/jun2019'
  get 'calendar/jun2018'
  get 'calendar/jun2017'
  get 'calendar/jun2016'
  get 'calendar/jun2015'
  get 'calendar/jul'
  get 'calendar/jul2021'
  get 'calendar/jul2020'
  get 'calendar/jul2019'
  get 'calendar/jul2018'
  get 'calendar/jul2017'
  get 'calendar/jul2016'
  get 'calendar/jul2015'
  get 'calendar/aug'
  get 'calendar/aug2021'
  get 'calendar/aug2020'
  get 'calendar/aug2019'
  get 'calendar/aug2018'
  get 'calendar/aug2017'
  get 'calendar/aug2016'
  get 'calendar/aug2015'
  get 'calendar/sep'
  get 'calendar/sep2021'
  get 'calendar/sep2020'
  get 'calendar/sep2019'
  get 'calendar/sep2018'
  get 'calendar/sep2017'
  get 'calendar/sep2016'
  get 'calendar/sep2015'
  get 'calendar/oct'
  get 'calendar/oct2021'
  get 'calendar/oct2020'
  get 'calendar/oct2019'
  get 'calendar/oct2018'
  get 'calendar/oct2017'
  get 'calendar/oct2016'
  get 'calendar/oct2015'
  get 'calendar/nov'
  get 'calendar/nov2021'
  get 'calendar/nov2020'
  get 'calendar/nov2019'
  get 'calendar/nov2018'
  get 'calendar/nov2017'
  get 'calendar/nov2016'
  get 'calendar/nov2015'
  get 'calendar/dec'
  get 'calendar/dec2021'
  get 'calendar/dec2020'
  get 'calendar/dec2019'
  get 'calendar/dec2018'
  get 'calendar/dec2017'
  get 'calendar/dec2016'
  get 'calendar/dec2015'
  get 'calendar/ddd_q2'
  get 'calendar/ddd_q3'
  get 'calendar/ddd_q4'
  get 'calendar/report'
  get 'calendar/report2021'
  get 'calendar/report2020'
  get 'calendar/report2019'
  get 'calendar/report2018'
  get 'calendar/report2017'
  get 'calendar/report2016'
  get 'calendar/report2015'

  resources :punches
  get 'ltfa/index'
  get 'ltfa/jan'
  get 'ltfa/feb'
  get 'ltfa/mar'
  get 'ltfa/apr'
  get 'ltfa/may'
  get 'ltfa/jun'
  get 'ltfa/jul'
  get 'ltfa/aug'
  get 'ltfa/sep'
  get 'ltfa/oct'
  get 'ltfa/nov'
  get 'ltfa/dec'
  get 'ltfa/ltfatwentytwenty'

  resources :activityreports
  get 'monthlybilled/index'
  devise_for :controllers
  resources :authorizations
  get 'unassigned/index'
  get 'logs/index'
  get 'ltfa/show'
  root 'pages#home'



  get 'ee/report'
  get 'authorizations/report_LTFA_TwentyTwenty'

    devise_for :users

  get 'openvoucher/index'
  get 'graphs/index'
  get 'reports/index'
  get 'monthly/index'
  get 'unpaid/index'
  get 'completed/index'
  get 'counselor/index'
  get 'pp/index'
  get 'csv/index'
  get 'timesheets/index'
  get 'cbwe/index'
  get 'ddd/index'
  get 'jobcoaches/index'

app/models/intervention.rb
class Intervention < ApplicationRecord
	  acts_as_paranoid

    validates :dateOfIntervention, presence: true
    validates :employeeID, presence: true
    validates :workAuthorizationID, presence: true

    def self.to_csv
    attributes = %w{
interventionID
employeeID
EmploymentHistoryID
employerID
workAuthorizationID
dateOfIntervention
startTime
endTime
jobRequirements
skillsStatus
interventionDescription
clientProgress
generalComments
prePlacementActivityID
ActivityConductedID
    }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end


   def self.import(file)
     CSV.foreach(file.path, headers: true) do | row |
        Intervention.create! row.to_hash
     end
   end

end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: [:show, :edit, :update, :destroy]
  # GET /interventions
  # GET /interventions.json
  def index
    @interventions = Intervention.all

    respond_to do |format|
       format.html
       format.csv { send_data @interventions.to_csv , filename: "interventions-#{Date.today}.csv"}
    end
  end

  def deleted
    @interventions = Intervention.only_deleted
  end

  # GET /interventions/1
  # GET /interventions/1.json
  def show
    @employees = Employee.all
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
    @interventions = Intervention.all
    @authorizations = Authorization.all
    @employees = Employee.all
    @authid = params[:authid]
    @jobRequirements_old = params[:jobRequirements_old]
    @skillsStatus_old = params[:skillsStatus_old]
    @interventionDescription_old = params[:interventionDescription]
    @clientProgress_old = params[:clientProgress]
    @generalComments_old = params[:generalComments]
    @serviceType = params[:serviceType]
  end

  # GET /interventions/1/edit
  def edit
    @employees = Employee.all
    @authid = params[:authid]
    @interventions = Intervention.all
    @authorizations = Authorization.all

  end

  # POST /interventions
  # POST /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)
    @authid = params[:authid]
    @employees = Employee.all

    respond_to do |format|
      if @intervention.save
         format.html { redirect_to @intervention, notice: 'Intervention was successfully created.' }
	# <td>  <button type="button" class="btn btn-light"><%= link_to "Calendar", controller: "calendar", action: "oct", employee: "#{employee.id}" %></button> </td>
        #format.html { redirect_to "authorizations", action: @authid  }
       format.json { render :show, status: :created, location: @intervention }
	open('log.txt', 'a') do |f|; f <<  Time.now.to_s + " " + current_user.email + " " + request.remote_ip + " CREATED intervention " + @intervention.id.to_s + "\n"; end

      else
        format.html { render :new }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1
  # PATCH/PUT /interventions/1.json
  def update
	       @employees = Employee.new

    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1
  # DELETE /interventions/1.json
  def destroy
     @authid = params[:authid]
    @intervention.destroy
    respond_to do |format|
      #format.html { redirect_to interventions_url, notice: 'Intervention was successfully destroyed.' }
      format.html { redirect_to :controller => "authorizations", :action => @authid, notice: '@authid'  }
      # format.html { redirect_to "/authorizations/"@authid }
 
  
       #format.html { redirect_to @authorizations, notice: 'Intervention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
   Intervention.import(params[:file])
   redirect_to interventions_path, notice: "Added Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intervention_params
      params.require(:intervention).permit(:interventionID, :employeeID, :EmploymentHistoryID, :employerID, :workAuthorizationID, :dateOfIntervention, :startTime, :endTime, :jobRequirements, :skillsStatus, :interventionDescription, :clientProgress, :generalComments, :prePlacementActivityID, :ActivityConductedID, :service)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/deleted.html.erb
<p id="notice"><%= notice %></p>
<style>
body {background-color: #C0C0C0;}
</style>

<h1>Interventions</h1>
<!-- <h3> Import</h3> -->
<%#= form_tag import_interventions_path, multipart: true do %>
   <%#= file_field_tag :file %>
   <%#= submit_tag "Upload" %>
<%# end %>
<br>
<%= @interventions.count %>
<table>
  <thead>
    <tr>
      <th>Interventionid</th>
      <th>Employeeid</th>
      <th>Employmenthistoryid</th>
      <th>Employerid</th>
      <th>Workauthorizationid</th>
      <th>Dateofintervention</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Jobrequirements</th>
      <th>Skillsstatus</th>
      <th>Interventiondescription</th>
      <th>Clientprogress</th>
      <th>Generalcomments</th>
      <th>Preplacementactivityid</th>
      <th>Activityconductedid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.interventionID %></td>
        <td><%= intervention.employeeID %></td>
        <td><%= intervention.EmploymentHistoryID %></td>
        <td><%= intervention.employerID %></td>
        <td><%= intervention.workAuthorizationID %></td>
        <td><%= intervention.dateOfIntervention %></td>
        <td><%= intervention.startTime %></td>
        <td><%= intervention.endTime %></td>
        <td><%= intervention.jobRequirements %></td>
        <td><%= intervention.skillsStatus %></td>
        <td><%= intervention.interventionDescription %></td>
        <td><%= intervention.clientProgress %></td>
        <td><%= intervention.generalComments %></td>
        <td><%= intervention.prePlacementActivityID %></td>
        <td><%= intervention.ActivityConductedID %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention,authid: "#{ intervention.workAuthorizationID}") %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>
<% open('log.txt', 'a') do |f|; f <<  Time.now.to_s + " " + current_user.email + " " + request.remote_ip + " is EDITING an intervention " + @intervention.id.to_s + "\n"; end %>

<%= render 'form', intervention: @intervention %>

<%#= link_to 'Show', @intervention %>
<%#= link_to "Voucher", controller: "authorizations", action: "show", id: @intervention.workAuthorizationID %>
<button type="button" class="btn btn-light"><%= link_to "Back to Voucher", controller: "authorizations", action: "show", id: @authid %></button>

<%#= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>
<style>
body {background-color: #C0C0C0;}
</style>

<h1>Interventions</h1>
<a href="/manager/index"><button type="button" class="btn btn-primary">Manager Dashboard</button></a>

<h3> Import</h3>
<%= form_tag import_interventions_path, multipart: true do %>
   <%= file_field_tag :file %>
   <%= submit_tag "Upload" %>
<% end %>
<br>
<%= @interventions.count %>
<table>
  <thead>
    <tr>
      <th>Interventionid</th>
      <th>Employeeid</th>
      <th>Employmenthistoryid</th>
      <th>Employerid</th>
      <th>Workauthorizationid</th>
      <th>Dateofintervention</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Jobrequirements</th>
      <th>Skillsstatus</th>
      <th>Interventiondescription</th>
      <th>Clientprogress</th>
      <th>Generalcomments</th>
      <th>Preplacementactivityid</th>
      <th>Activityconductedid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.interventionID %></td>
        <td><%= intervention.employeeID %></td>
        <td><%= intervention.EmploymentHistoryID %></td>
        <td><%= intervention.employerID %></td>
        <td><%= intervention.workAuthorizationID %></td>
        <td><%= intervention.dateOfIntervention %></td>
        <td><%= intervention.startTime %></td>
        <td><%= intervention.endTime %></td>
        <td><%= intervention.jobRequirements %></td>
        <td><%= intervention.skillsStatus %></td>
        <td><%= intervention.interventionDescription %></td>
        <td><%= intervention.clientProgress %></td>
        <td><%= intervention.generalComments %></td>
        <td><%= intervention.prePlacementActivityID %></td>
        <td><%= intervention.ActivityConductedID %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention,authid: "#{ intervention.workAuthorizationID}") %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New Intervention</h1>
<% open('log.txt', 'a') do |f|; f <<  Time.now.to_s + " " + current_user.email + " " + request.remote_ip + " creating intervention " + @intervention.to_s + "\n"; end %>

<%= render 'form', intervention: @intervention %>
<% if @authid != nil %>
<%= link_to "Back to Voucher", controller: "authorizations", action: "show", id: @authid %>
<% end %>
<%#= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<% open('log.txt', 'a') do |f|; f << Time.now.to_s + " " + current_user.email + " " + request.remote_ip + " loaded interventions SHOW " + @intervention.id.to_s + "\n"; end %>

<style>
body {background-color: #C0C0C0;}

</style>
<!--
<p>
  <strong>id:</strong>
  <%= @intervention.interventionID %>
</p>
-->
<p>
  <strong>Job Coach : </strong>
  <% @jobcoach = @employees.where(id: @intervention.employeeID) %>
  <% @jobcoach.each do |jobcoach| %>
	  <b><%= jobcoach.employee %></b>
  <% end %>	  
  <%#= @intervention.employeeID %>
</p>
<!--
<p>
  <strong>Employmenthistoryid:</strong>
  <%= @intervention.EmploymentHistoryID %>
</p>
-->
<p>
  <strong>Employer id:</strong>
  <%= @intervention.employerID %>
</p>

<p>
  <strong>Voucher id:</strong>
  <button type="button" class="btn btn-light"><%= link_to @intervention.workAuthorizationID, controller: "authorizations", action: "show", id: @intervention.workAuthorizationID %></button><br>

  <% @intervention.workAuthorizationID %>
</p>

<p>
  <strong>Date of Intervention:</strong>
  <%= @intervention.dateOfIntervention %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @intervention.startTime %>
</p>

<p>
  <strong>End Time:</strong>
  <%= @intervention.endTime %>
</p>

<p>
  <strong>Job Requirements:</strong>
  <%= @intervention.jobRequirements %>
</p>

<p>
  <strong>Skill Status:</strong>
  <%= @intervention.skillsStatus %>
</p>

<p>
  <strong>Intervention Description:</strong>
  <%= @intervention.interventionDescription %>
</p>

<p>
  <strong>Client Progress:</strong>
  <%= @intervention.clientProgress %>
</p>

<p>
  <strong>General Comments:</strong>
  <%= @intervention.generalComments %>
</p>

<p>
  <strong>Preplacementactivityid:</strong>
  <%= @intervention.prePlacementActivityID %>
</p>
<!--
<p>
  <strong>Activityconductedid:</strong>
    <%= @intervention.ActivityConductedID %>
  </p>
  -->
<%#= link_to 'Edit', edit_intervention_path(@intervention) %> 
<%#= link_to 'Back', interventions_path %>
<button type="button" class="btn btn-light"><%= link_to "Back_to_voucher", controller: "authorizations", action: "show", id: @intervention.workAuthorizationID %></button>
<%#= link_to @intervention.workAuthorizationID, controller: "authorizations", action: "show", id: @intervention.workAuthorizationID %>

<%= link_to 'Edit', edit_intervention_path(@intervention) %>
<%#= link_to 'Back', interventions_path %>